# Generated by Django 5.2.11 on 2026-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'План года',
            },
        ),
    ]
