# Generated by Django 5.2.11 on 2026-03-21 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_yearplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearplan',
            options={'verbose_name': 'План года', 'verbose_name_plural': 'План года'},
        ),
    ]
