# Generated by Django 5.2.11 on 2026-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_yearplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplan',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
