# Generated by Django 5.2.11 on 2026-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_yearplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearplan',
            name='description',
            field=models.TextField(),
        ),
    ]
