# Generated by Django 5.2.11 on 2026-03-31 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_yearplan_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
