# Generated by Django 5.2.11 on 2026-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='todo', max_length=20)),
                ('deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
            },
        ),
    ]
