# Generated by Django 5.2.11 on 2026-03-22 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministries', '0002_ministrygoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministrygoals',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ministries.ministries'),
        ),
    ]
